/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function extract(reader: Buffer, filename: string): number
export function extractPdf(reader: Buffer): number
